name: ristu_intern_challenge
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cookie_jar: ^4.0.8
  dartz: ^0.10.1
  dio: ^5.4.0
  dio_cookie_manager: ^3.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  freezed: ^2.4.5
  gap: ^3.0.1
  get: ^4.6.5
  get_it: ^7.6.0
  google_fonts: ^6.1.0
  intl: ^0.18.0
  introduction_screen: ^3.1.11
  json_annotation: ^4.8.1
  jwt_decode: ^0.3.1
  lottie: ^3.1.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins.ttf
  assets:
    - assets/json/
    - assets/img/
    - assets/svg/
